// <auto-generated />
namespace PIMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Morevalidationplzdontbreak : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Morevalidationplzdontbreak));
        
        string IMigrationMetadata.Id
        {
            get { return "201804241227273_More validation, plz dont break"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
