// <auto-generated />
namespace PIMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Passwordgonefromadmin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Passwordgonefromadmin));
        
        string IMigrationMetadata.Id
        {
            get { return "201804191244089_Password gone from admin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
